language: node_js
before_install:
  - npm i yarn -g
node_js:
  - "lts/*"
before_script:
  - sudo apt-get update -qq
script:
  - npm run lint
  - npm run build
  - ls -lsah dist/
deploy:
  provider: releases
  api_key: $gh_token
  file:
    - dist/vuenote.zip
  skip_cleanup: true
  on:
    repo: ExNG/vuenote
    tags: true
