language: node_js
node_js:
  - "lts/*"
before_script:
  - sudo apt-get update -qq
script:
  - npm run test
  - npm run testBuild
  - ls -lsah dist/
# before/_deploy:
  - npm run build
  - ls -lsah dist/
deploy:
  provider: releases
  api_key: $gh_token
  file:
    # - vuenote-darwin-x64.zip
    - dist/vuenote-linux-x64.zip
    - dist/vuenote-win32-x64.zip
    - dist/vuenote_amd64.deb
  skip_cleanup: true
  on:
    repo: ExNG/vuenote
    tags: true
