language: node_js
node_js:
  - "lts/*"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install wine -y
  - npm install -g quasar-cli
install:
  - npm install
  - cd electron && npm install
script:
  - cd ..
  - quasar build
  - cd electron && quasar build
