language: node_js
node_js:
  - "lts/*"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install wine zip -y
  - npm install -g quasar-cli
install:
  - npm install
  - cd electron && npm install
script:
  - cd ..
  - quasar build
  - cd electron && quasar build
  - cd dist
  - zip -r vuenite-darwin-x64.zip Vuenite-darwin-x64/
  - zip -r vuenite-linux-x64.zip Vuenite-linux-x64/
  - zip -r vuenite-win32-x64.zip Vuenite-win32-x64/
deploy:
  provider: releases
  api_key: $gh_token
  file:
    - vuenite-darwin-x64.zip
    - vuenite-linux-x64.zip
    - vuenite-win32-x64.zip
  skip_cleanup: true
  on:
    repo: ExNG/vuenite
    tags: true
