language: node_js
node_js:
  - "lts/*"
before_script:
  - sudo apt-get update -qq
script:
  - npm run testBuild
  - ls -lsah dist/ -R
before_deploy:
  - npm run build
  - ls -lsah dist/ -R
deploy:
  provider: releases
  api_key: $gh_token
  file:
    # - vuenote-darwin-x64.zip
    - vuenote-linux-x64.zip
    - vuenote-win32-x64.zip
    - vuenote_amd64.deb
  skip_cleanup: true
  on:
    repo: ExNG/vuenote
    tags: true
