language: node_js
node_js:
  - "lts/*"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install wine zip -y
  - npm install -g quasar-cli
install:
  - npm install
script:
  - quasar build -m electron -t ios --target all
  - cp src/statics/icon.png dist/electron-ios/Vuenote-darwin-x64/icon.png
  - cp src/statics/icon.png dist/electron-ios/Vuenote-linux-x64/icon.png
  - cp src/statics/icon.png dist/electron-ios/Vuenote-win32-x64/icon.png
  - cd dist
  - zip -r vuenote-darwin-x64.zip electron-ios/Vuenote-darwin-x64/ -9
  - zip -r vuenote-linux-x64.zip electron-ios/Vuenote-linux-x64/ -9
  - zip -r vuenote-win32-x64.zip electron-ios/Vuenote-win32-x64/ -9
deploy:
  provider: releases
  api_key: $gh_token
  file:
    - vuenote-darwin-x64.zip
    - vuenote-linux-x64.zip
    - vuenote-win32-x64.zip
  skip_cleanup: true
  on:
    repo: ExNG/vuenote
    tags: true
